baseURL = 'https://p23.netlify.app/'

languageCode = 'pt-br'

title = 'Cássio23'

theme = 'ananke'


[params]
  text_color = "dark-gray"
  author = "Cássio Sanguini Sergio"
  favicon = ""
  site_logo = ""
  description = "Candidato."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-purple"
  recent_posts_number = 3


